### ISSUE TITLE
Add option to limit dependency depth to 0, 1, 2 etc.

### ISSUE THREAD

**Issue by tobiasbueschel** [davglass/license-checker#120]
It would be great to only check the licenses that are declared in `package.json` and not all its peer dependencies.

Is there currently a way to achieve this @davglass?

**Comment by davglass** [comment]
There isn't a way to do this at the moment, but I think you can add a `depth` to the `read-installed` module not really sure.

That being said, I never added this and am pretty reluctant to add it as it's pretty harmful to do this. A project is bound by all licensing of all the code that it uses, allowing people to "skip" dependencies would give them a false sense of security knowing that they are following proper licensing practices but they are not since they are skipping things that they very much should care about.

**Comment by tobiasbueschel** [comment]
Thanks for the explanation @davglass - that actually makes sense! I will close this issue (for now).

Cheers ✌️
