### ISSUE TITLE
Work around monorepos

### ISSUE THREAD

**Issue by honzajavorek** [davglass/license-checker#134]
There is a common issue with monorepos, described in https://github.com/lerna/lerna/issues/1213. Would it make sense for license checker to work around the issue? It could somehow check whether the project is/isn't a monorepo and in case the license is missing, it could look it up in the root of the monorepo.

**Comment by davglass** [comment]
Not sure what you expect this module to do. It scans the installed packages, it never looks outside of the installed path for anything. So it couldn't check the root of a monorepo since it never leaves the disk. If the package doesn't ship with a license in the source, then it's not technically licensed properly.

**Comment by honzajavorek** [comment]
Hmm, I guess you're right. This really needs to be fixed with the projects and the tooling around monorepos 😞

**Comment by MarkAshraf96** [comment]
@davglass
Sorry to bring you back to this old issue,
The problem I found with monorepos is, although the license files are included in each package, the repository url in the package.json is the monorepo url and not the package url. I think the best practice I saw had this format:

```
"repository": {
    "type": "git",
    "url": "https://github.com/monorepo.git",
    "directory": "packages/packageName"
  }
```
So I believe the license-checker is not handling this situation, it looks in the monorepo url, instead of adding the directory to it.
The output: it fetches the license file from the monorepo url if it exists, if no license file it fetches the readme. Although it's highly uncommon but different packages in the same monorepo can have different license types if there is no license defined for the whole monorepo.
