### ISSUE TITLE
Option to list licenses only for dependencies in package.json

### ISSUE THREAD

**Issue by kimmobrunfeldt** [davglass/license-checker#17]
I would like an option to list licenses for "first" dependencies in the dependency tree. So in other words list dependencies only for the modules which are listed in package.json file's "dependencies".

**Comment by michaelsanford** [comment]
Dependencies at all levels *are* a valid thing to track, but the list that is produced is flat, which means I cannot readily identify which modules, from an implementation standpoint, offend our licensing policy because they contain an unusable dependency.

For instance: if we can't use GPL-licensed modules, and they only exist in dependencies, I would need to know which modules _ask for them_ so I can find or write an alternative.

**Comment by Kienz** [comment]
+1 Depth-Parameter would be nice!

**Comment by davglass** [comment]
I do agree about maintaining the tree as an option, but I can't bring myself to allow a `--depth` as it really would make this tool useless for those that really care about their licenses. All licenses of all code should be scanned, not just the top level. If you bring in a dependency of a dependency that brings in a license that is harmful to you or your employer and it was missed by only scanning the top level, this could end badly.

I'm going to close this for now as I don't see this as the "right thing to do".
