### ISSUE TITLE
Feature Request: List licenses for dependencies, only

### ISSUE THREAD

**Issue by mwittig** [davglass/license-checker#21]
I would like to suggest a new option to list licenses for dependencies, only. In other words, the license for the module defined by package.json itself shall be excluded. Assuming this can be controlled by a command line option "--dependencies" this can be achieved easily by the following patch.

https://github.com/mwittig/license-checker/commit/01cde66943beb1c403c880fe8e001f90ca75526f

Of course, some additional code will be required to set the command line option. I am happy to do that if the feature request finds your acceptance. Please also advise further about test requirements in case.

**Comment by tstibbs** [comment]
@davglass can you give a quick example of how to use the filter please? I can't see anything in the docs.

My use-case is simply that I want to exclude "this" module from the outputted list - i.e. just include its dependencies. It's not trivial to filter out by name, because I have lots of different modules that it could be.
