### ISSUE TITLE
Excluding license types with commas in them.

### ISSUE THREAD

**Issue by michaelmelanson** [davglass/license-checker#70]
Some packages have license types with commas in them. One I've encountered is [rx-lite](https://github.com/Reactive-Extensions/RxJS), which lists its license as "Apache License, Version 2.0". Is there a way to exclude these with the `--exclude` flag? I don't know a way that isn't interpreted as separate "Apache License" and "Version 2.0" licenses.

**Comment by davglass** [comment]
Not sure I follow, can you explain it in more detail?

FYI, that module needs to patch it's package.json to make it `license` and a string instead of `licenses` and an `Array` (which is the old format):
https://github.com/Reactive-Extensions/RxJS/blob/master/modules/rx-lite/package.json#L15-L20

**Comment by zommerfelds** [comment]
I have the same issue. This happens when there is a comma inside a single license entry (e.g. [here](https://github.com/RedVentures/reduce/blob/master/package.json#L20)). Of course the root cause is that packages are not using a SPDX license identifier, but maybe it would be a good idea to support a "," character by for example interpreting an escape character like "\,".

**Comment by zommerfelds** [comment]
If you want I can update the regex to support that.
